apiVersion: v1
kind: ConfigMap
metadata:
  name: a2m4-config
  namespace: app2
data:
  application.properties: |-

    microservice.nextservices=0

    microservice.directreply.msgsize=5
    microservice.directreply.processingtime=5


