apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app2
  name: config-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get"]