kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name: app-1-cluster

nodes:
  - role: control-plane
    image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
    extraMounts:
    - hostPath: ./data_cp_c1
      containerPath: /tmp/data
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=17Gi,cpu=8
    labels:
      topology.kubernetes.io/region: cloud
      topology.kubernetes.io/zone: cloud1
  - role: worker
    image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
    extraMounts:
    - hostPath: ./data_w1_c1
      containerPath: /tmp/data
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=17Gi,cpu=8
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-aggregator-routing: "true"
    extraPortMappings:
      - containerPort: 32012
        hostPort: 15443
        protocol: TCP
      - containerPort: 32022
        hostPort: 80
        protocol: TCP
      - containerPort: 32032
        hostPort: 6443
        protocol: TCP
    labels:
      istioingress: enable
      istioeastwest: enable
      topology.kubernetes.io/region: cloud
      topology.kubernetes.io/zone: cloud1
    
kubeadmConfigPatches:
- |
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      authorization-mode: "AlwaysAllow"



