@startuml
top to bottom direction
'https://plantuml.com/object-diagram
object ApplicationProvider
object PlacementRequest{
 application id
 placed microservices
 entry clusters
}
object ControlEngine

object PlacementPolicy

object Microservice{
  microservice id
}
object Dataflow{
 start microservice id
 end microserivce id
}
object Datapath
object CompositeService

object Application{
    application id
}

object QoSParameter
object ResourceRequirements{
   cpu
   memory
   storage
   throughput
}

object Placement {
   microservice-device mapping
   pr completion levels
}

object MicroserviceLevelCommand{
    microservice id
}

object ApplicationLevelCommand{

}

object ServiceLevelCommand{

}

object ClusterData{
    device resources
    topology information
}

object DeployCommands

object Pod
object NameSpace
object Service
object Role
object RoleBinding
object ConfigMap
object VirtualService
object DestinationRule
object Gateway

object KubeResource
object IstioResource
object PlacementRestrictions



ApplicationProvider  --  "1..*" PlacementRequest : submits >
PlacementRequest -- "0..*" QoSParameter : contains >
PlacementRequest -- "0..*" PlacementRestrictions : contains >
PlacementRequest "1" -- "1" Application : is for >
PlacementRequest "1..*" --  ControlEngine : processes <
(PlacementRequest, ControlEngine). PlacementPolicy : using
PlacementPolicy. ClusterData : uses


Microservice "1..*" o-- "1" CompositeService : consists of <
Application  o-- "1..*" Microservice : consists of >
Application "1" o-- "1..*" CompositeService : has >
 Microservice "1" --o "1"ResourceRequirements : has >

Datapath "1..*" *-- "1" CompositeService : has <
Datapath "1" *-- "1..*" Dataflow : consists of >
Dataflow "1..*" -- "1" Application : has <


Microservice "1"--"1..*" MicroserviceLevelCommand : deployed using >
Application "1" --"1..*" ApplicationLevelCommand : has related >
CompositeService "1" -- "1..*" ServiceLevelCommand : achieve composition through >


PlacementPolicy  --  Placement : generates >
ControlEngine "1" -- "1..*" DeployCommands : executes >


(ControlEngine, DeployCommands).Placement : uses

DeployCommands --> ApplicationLevelCommand
DeployCommands --> MicroserviceLevelCommand
DeployCommands --> ServiceLevelCommand

ApplicationLevelCommand --> NameSpace
ApplicationLevelCommand --> Role
ApplicationLevelCommand --> RoleBinding

MicroserviceLevelCommand --> Pod

ServiceLevelCommand --> Service
ServiceLevelCommand --> VirtualService
ServiceLevelCommand --> Gateway
ServiceLevelCommand --> DestinationRule

NameSpace <-- KubeResource
Role <-- KubeResource
RoleBinding <-- KubeResource
Service <-- KubeResource
Pod <-- KubeResource
ConfigMap <-- KubeResource

Pod "1" -- "1" ConfigMap

VirtualService <-- IstioResource
Gateway <-- IstioResource
DestinationRule <-- IstioResource

@enduml
