apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: kind-fog1
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-kind-fog1
  namespace: istio-system
stringData:
  kind-edge1: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <------------------------>
        server: https://<PUBLIC_IP_OF_THE_VM>:6443
      name: kind-fog1
    contexts:
    - context:
        cluster: kind-fog1
        user: kind-fog1
      name: kind-fog1
    current-context: kind-fog1
    kind: Config
    preferences: {}
    users:
    - name: kind-fog1
      user:
        token: <-------------------------->
---
